flask_login_wtf/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(200), unique=False, nullable=False)
    created_date = db.Column(db.DateTime, unique=False, nullable=False)
    last_login = db.Column(db.DateTime, unique=False, nullable=True)

    def set_password(self, password):
        self.password = generate_password_hash(password, method='sha256')

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User {}>'.format(self.name)

flask_login_wtf/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length


class SignupForm(FlaskForm):
    name = StringField('Nome', validators=[DataRequired()])
    email = StringField('Email', validators=[
                                    DataRequired(), 
                                    Email(message="Informe um email válido"), 
                                    Length(min=6, message="Email precisa ter pelo menos 6 caracteres")
                                ]
    )
    password = PasswordField('Senha', validators=[DataRequired()])
    confirm = PasswordField('Confirme sua senha', validators=[
                                                    DataRequired(), 
                                                    EqualTo('password', message="Senhas não batem")
                                                ]
    )
    submit = SubmitField('Registrar')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[
                                    DataRequired(), 
                                    Email(message="Informe um email válido"), 
                                    Length(min=6, message="Email precisa ter pelo menos 6 caracteres")
                                ]
    )
    password = PasswordField('Senha', validators=[DataRequired()])
    submit = SubmitField('Login')

flask_login_wtf/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()

def init_app():
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object("config.Config")

    db.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        from . import routes
        from .authentication import auth

        app.register_blueprint(auth.auth_blueprint)
        app.register_blueprint(routes.main_blueprint)

        db.create_all()

        return app

flask_login_wtf/auth.py
from flask import Blueprint, render_template, redirect
from flask.globals import request
from flask.helpers import url_for, flash
from flask_login import login_user, current_user
from datetime import datetime
from .forms import SignupForm, LoginForm
from .models import User
from . import db, login_manager

auth_blueprint = Blueprint('auth_blueprint', __name__, template_folder='templates', static_folder='static')

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_blueprint.app'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')

            return redirect(next_page or url_for('main_blueprint.app'))

        flash('Email/senha inválidos')
        return redirect(url_for('auth_blueprint.login'))
    
    return render_template(
        'login.html',
        form = form
    )

@auth_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()

        if existing_user is None:
            user = User(
                name=form.name.data,
                email=form.email.data,
                created_date=datetime.now()
            )
            user.set_password(form.password.data)

            db.session.add(user)
            db.session.commit()
            login_user(user)

            return redirect(url_for('main_blueprint.app'))

        flash('Já existe um registro com esse email')

    return render_template(
        'signup.html',
        form = form
    )

@login_manager.user_loader
def load_user(user_id):
    if user_id is not None:
        return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    flash("Você precisa estar logado para continuar nesta página")
    return redirect(url_for('auth_blueprint.login'))

flask_login_wtf/authentication/auth.py
from flask import Blueprint, render_template, redirect
from flask.globals import request
from flask.helpers import url_for, flash
from flask_login import login_user, current_user
from datetime import datetime
from flask_login_wtf.forms import SignupForm, LoginForm
from flask_login_wtf.models import User
from flask_login_wtf import db, login_manager

auth_blueprint = Blueprint('auth_blueprint', __name__, template_folder='templates', static_folder='static')

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_blueprint.app'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')

            return redirect(next_page or url_for('main_blueprint.app'))

        flash('Email/senha inválidos')
        return redirect(url_for('auth_blueprint.login'))
    
    return render_template(
        'login.html',
        form = form
    )

@auth_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()

        if existing_user is None:
            user = User(
                name=form.name.data,
                email=form.email.data,
                created_date=datetime.now()
            )
            user.set_password(form.password.data)

            db.session.add(user)
            db.session.commit()
            login_user(user)

            return redirect(url_for('main_blueprint.app'))

        flash('Já existe um registro com esse email')

    return render_template(
        'signup.html',
        form = form
    )

@login_manager.user_loader
def load_user(user_id):
    if user_id is not None:
        return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    flash("Você precisa estar logado para continuar nesta página")
    return redirect(url_for('auth_blueprint.login'))

flask_login_wtf/routes.py
from flask import Blueprint
from flask.helpers import url_for
from flask.templating import render_template
from flask_login import current_user, login_required
from flask_login.utils import logout_user
from werkzeug.utils import redirect

main_blueprint = Blueprint('main_blueprint', __name__, template_folder='templates', static_folder='static')

@main_blueprint.route('/app', methods=['GET'])
@login_required
def app():
    return render_template(
        'app.html',
        current_user=current_user
    )

@main_blueprint.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_blueprint.login'))

flask_login_wtf/templates/app.html
{% extends 'main.html' %}

{% block content %}
    <div class="container h-100">
        <div class="row justify-content-md-center h-100">
            <div class="col-lg-5 col-md-9 col-sm-10">
                <h1>Você logou com sucesso</h1>
                <a href="{{ url_for('main_blueprint.logout') }}">Clique aqui para sair</a>
            </div>
        </div>
    </div>
{% endblock %}

flask_login_wtf/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous"
        />

        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    </head>
    <body>
        <main class="h-100">
            <div class="container-fluid h-100">
                {% block content %} {% endblock %}
            </div>
        </main>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"
        ></script>
    </body>
</html>